# Generated by Django 5.1.1 on 2024-10-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADMIN',
            fields=[
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.user',),
        ),
        migrations.CreateModel(
            name='COURIER',
            fields=[
            ],
            options={
                'verbose_name': 'Courier',
                'verbose_name_plural': 'Couriers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.user',),
        ),
        migrations.CreateModel(
            name='MODERATOR',
            fields=[
            ],
            options={
                'verbose_name': 'Moderator',
                'verbose_name_plural': 'Moderators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.user',),
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': 'Operators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.user',),
        )
    ]
