# Generated by Django 5.1.1 on 2024-10-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_admin_courier_moderator_operator_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
