# Generated by Django 5.1.1 on 2024-10-21 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operator',
        ),
        migrations.CreateModel(
            name='Operatorproxy',
            fields=[
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': 'Operators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.user',),
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Region',
            new_name='region',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(max_length=9, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
