# Generated by Django 5.1.1 on 2024-10-23 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_order_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='apps.stream'),
        ),
    ]
